
# Ideas

Add St Helens image as used in plotly?
https://github.com/matplotlib/viscm/tree/master/viscm/examples

The 'IsolatedGalaxy' image is a very good test image which can look very different depending on the colormap.
http://yt-project.org/doc/visualizing/colormaps/index.html
The data is in a mysterious (3D?) format.  Perhaps one of these images could be cropped and rasterized and back-transformed from color to numerical value.
http://yt-project.org/doc/_images/cmap_images__Projection_Greys_r.png
http://yt-project.org/doc/_images/cmap_images__Projection_BuPu.png
http://yt-project.org/doc/_images/cmap_images__Projection_Pastels.png
http://yt-project.org/doc/_images/cmap_images__Projection_Pastel2.png


In pal.test, add discrete=TRUE to prevent interpolation

TODO: gist_earth

Peter Karpov: In Search of a Perfect Colormap
http://inversed.ru/Blog_2.htm

http://mkweb.bcgsc.ca/

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/_cm.py


# ----------------------------------------------------------------------------
# ----------------------------------------------------------------------------

# Misc

Color Schemes Appropriate for Scientific Data Graphics
http://geog.uoregon.edu/datagraphics/color_scales.htm

d3-scale Interesting palettes at bottom
https://github.com/d3/d3-scale/blob/master/README.md

Choosing colormaps
http://matplotlib.org/users/colormaps.html


# People


## Peter Kovesi

Palettes defined in csv format here:
http://peterkovesi.com/projects/colourmaps/index.html

Some interesting comments about the palettes
https://github.com/peterkovesi/PerceptualColourMaps.jl/blob/master/src/cmap.jl


## Matteo Niccoli

Credit to Matteo Niccoli as the author and mycarta.wordpress.com
https://mycarta.wordpress.com/2012/05/29/the-rainbow-is-dead-long-live-the-rainbow-series-outline/

Trimmed version of cubicyf palette
https://www.mathworks.com/matlabcentral/fileexchange/28982-perceptually-improved-colormaps/content/pmkmp/pmkmp.m

Non-trimmed version here
https://github.com/rikrd/matlab/blob/master/output/pmkmp/pmkmp.m


## Kristen Thyng

cmocean, MIT license
http://matplotlib.org/cmocean/
https://github.com/kthyng/cmocean

Actual color definitions are here:
https://github.com/kthyng/cmocean/tree/master/cmocean/rgb

PlotCon 2016 talk
https://www.youtube.com/watch?v=o9KxYxROSgM


## Paul Tol

https://personal.sron.nl/~pault


# StackExchange

http://stackoverflow.com/questions/470690/how-to-automatically-generate-n-distinct-colors

http://stackoverflow.com/questions/2328339/how-to-generate-n-different-colors-for-any-natural-number-n

http://graphicdesign.stackexchange.com/questions/3682/where-can-i-find-a-large-palette-set-of-contrasting-colors-for-coloring-many-d

http://mathematica.stackexchange.com/questions/64513/is-there-an-easy-way-to-use-matteo-niccolis-perceptual-color-maps-for-2d-plots

http://stackoverflow.com/questions/7251872/is-there-a-better-color-scale-than-the-rainbow-colormap

http://stackoverflow.com/questions/13968520/color-selection-for-matplotlib-that-prints-well

Linked to 9563711
http://stackoverflow.com/questions/15282580/how-to-generate-a-number-of-most-distinctive-colors-in-r

Posted 'pals' image here:
http://stackoverflow.com/questions/9563711/r-color-palettes-for-many-data-classes/41230685


# R packages

## beyonce
https://github.com/dill/beyonce
An R package for beyoncepalettes.tumblr.com

## catecolors
https://github.com/btupper/catecolors
Colors from various sources that are suitable for displaying categorical (qualitative) colors.

## ggsci
https://github.com/road2stat/ggsci
ggsci offers a collection of ggplot2 color palettes inspired by scientific journals, data visualization libraries, and science fiction TV shows.

## oce
https://github.com/dankelley/oce/
Contains R version of cmocean colormaps

## palettetown
https://github.com/timcdlucas/palettetown
An R package providing pokemon colour palettes.

## palr
https://github.com/AustralianAntarcticDivision/palr
palr provides color palettes for data, based on some well known remotely sensed data sets for sea ice concentration, sea surface temperature and chlorophyll-a.

## Polychrome
https://rdrr.io/rforge/Polychrome/man/viewers.html
install.packages("Polychrome", repos="http://R-Forge.R-project.org")

## qualpalr
qualpalr generates distinct qualitative color palettes
https://cran.r-project.org/web/packages/qualpalr/vignettes/introduction.html
https://github.com/jolars/qualpalr

## randomcoloR
https://github.com/ronammar/randomcoloR
An R package for generating attractive and distinctive colors.

## RColorBrewer
Has one main function brewer.pal to access ColorBrewer palettes.

## RSkittleBrewer
https://github.com/alyssafrazee/RSkittleBrewer
Candy-themed palettes.

## spatstat
Contains Kovesi's colormaps.

## cetcolor
https://cran.rstudio.com/web/packages/cetcolor/vignettes/cet_color_schemes.html
https://cran.rstudio.com/web/packages/cetcolor/vignettes/cet_color_schemes.html
Contains Kovesi's colormaps.

## wesanderson
https://github.com/karthik/wesanderson
Wes Anderson palettes.
